version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-ptodo"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: todo_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_URL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: todo
      DB_USERNAME: todo
      DB_PASSWORD: todo
    ports:
      - "8080:8000"
    volumes:
      - backend_vendor:/app/vendor   # speeds up rebuilds

  frontend:
    build:
      context: ./frontend
    container_name: todo_frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8080/api
    ports:
      - "3000:3000"

volumes:
  db_data:
  backend_vendor:
